### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Yeager28** [muralianand12345/Discord-TicketBot-EliteX#6]
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
customer@sparkedhost~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
NodeJS version: v16.14.2
customer@sparkedhost~ Server marked as running...
NPM version: 8.5.0
Yarn version: 22.18
Git version: 2.20.1
customer@sparkedhost:~# if [[ -d .git ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then npm install --production; fi; node /home/container/${STARTUP_FILE}
npm WARN deprecated @discordjs/collection@0.1.6: no longer supported
npm WARN deprecated @sapphire/snowflake@1.3.6: This version has been automatically deprecated by @favware/npm-deprecate. Please use a newer version.
npm WARN deprecated @discordjs/form-data@3.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated @discordjs/collection@0.2.4: no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @discordjs/rest@0.1.0-canary.0: no longer supported
npm WARN deprecated @discordjs/builders@0.6.0: no longer supported
npm WARN deprecated discord-api-types@0.18.1: No longer supported. Install the latest release (0.20.2)
npm WARN deprecated discord.js@13.2.0: no longer supported
npm WARN deprecated discord-api-types@0.22.0: No longer supported. Install the latest release!
npm WARN deprecated discord-api-types@0.23.1: No longer supported. Install the latest release!
npm WARN deprecated discord-api-types@0.24.0: No longer supported. Install the latest release!
added 157 packages, and audited 158 packages in 47s
11 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 8.5.0 -> 8.16.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.16.0
npm notice Run npm install -g npm@8.16.0 to update!
npm notice 

removed 2 packages, and audited 156 packages in 3s
11 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
add has been loaded
announce has been loaded
avatar has been loaded
ban has been loaded
boomer has been loaded
botinfo has been loaded
darkchat has been loaded
emojilist has been loaded
id has been loaded
invite has been loaded
kick has been loaded
meme has been loaded
ping has been loaded
reactionrole has been loaded
rolecheck has been loaded
serverinfo has been loaded
shutdown has been loaded
ticketmessagefivem has been loaded
ticketmessageredm has been loaded
userinfo has been loaded
weather has been loaded
DiscordAPIError[50035]: Invalid Form Body
application_id[NUMBER_TYPE_COERCE]: Value "undefined" is not snowflake.
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:99:20) {
  rawError: {
    code: 50035,
    errors: { application_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/undefined/commands'
}
/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:249
        throw new Error(WSCodes[error.code]);
              ^
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:249:15)
    at async Client.login (/home/container/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
customer@sparkedhost~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
customer@sparkedhost~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
NodeJS version: v16.14.2
customer@sparkedhost~ Server marked as running...
NPM version: 8.5.0
Yarn version: 22.18
Git version: 2.20.1
customer@sparkedhost:~# if [[ -d .git ]]; then git pull; fi; if [[ ! -z ${NODE_PACKAGES} ]]; then npm install ${NODE_PACKAGES}; fi; if [ -f /home/container/package.json ]; then npm install --production; fi; node /home/container/${STARTUP_FILE}
added 2 packages, and audited 158 packages in 9s
11 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.

removed 2 packages, and audited 156 packages in 3s
11 packages are looking for funding
  run `npm fund` for details
2 moderate severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
add has been loaded
announce has been loaded
avatar has been loaded
ban has been loaded
boomer has been loaded
botinfo has been loaded
darkchat has been loaded
emojilist has been loaded
id has been loaded
invite has been loaded
kick has been loaded
meme has been loaded
ping has been loaded
reactionrole has been loaded
rolecheck has been loaded
serverinfo has been loaded
shutdown has been loaded
ticketmessagefivem has been loaded
ticketmessageredm has been loaded
userinfo has been loaded
weather has been loaded
DiscordAPIError[50035]: Invalid Form Body
application_id[NUMBER_TYPE_COERCE]: Value "undefined" is not snowflake.
    at SequentialHandler.runRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:198:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SequentialHandler.queueRequest (/home/container/node_modules/@discordjs/rest/dist/lib/handlers/SequentialHandler.js:99:20) {
  rawError: {
    code: 50035,
    errors: { application_id: [Object] },
    message: 'Invalid Form Body'
  },
  code: 50035,
  status: 400,
  method: 'put',
  url: 'https://discord.com/api/v9/applications/undefined/commands'
}
/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:249
        throw new Error(WSCodes[error.code]);
              ^
Error [DISALLOWED_INTENTS]: Privileged intent provided is not enabled or whitelisted.
    at WebSocketManager.createShards (/home/container/node_modules/discord.js/src/client/websocket/WebSocketManager.js:249:15)
    at async Client.login (/home/container/node_modules/discord.js/src/client/Client.js:245:7) {
  [Symbol(code)]: 'DISALLOWED_INTENTS'
}
customer@sparkedhost~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 1
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.

**Comment by muralianand12345** [comment]
Make sure you enable the Bot's Intents in discord developer portal. 
[https://discord.com/developers/applications](url) 
@Yeager28
